//-----------------------------------------------------------------------------
// zx81dis
// Copyright (C) Paulo Custodio, 2023-2026
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#include "ass_emit_p.h"
#include "ass_parser.h"
#include "sysvars.h"
#include "utils.h"
#include "zfloat.h"
#include "zx81chars.h"
#include <array>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

static std::string string_to_zx81(const std::string& text,
                                  bool check_keywords,
                                  bool invert = false) {
    constexpr size_t INDENT = 24;
    constexpr size_t MAX_WIDTH = 80 - INDENT - 2;

    std::ostringstream oss;
    const char* p = text.c_str();
    size_t width = 0;
    while (*p) {
        if (p != text.c_str()) {
            oss << ",";
            width++;
        }

        std::string encoded;
        uint8_t code;
        if (!encode_zx81_char(p, check_keywords, code, SourceLoc())) {
            encoded = int8_to_hex(code);
            p++;  // skip the invalid character
        }
        else {
            if (invert) {
                code ^= 0x80;  // invert the character
            }
            encoded = zx81_char_name(code);
        }

        if (width + encoded.length() > MAX_WIDTH) {
            oss << " \\\n" << std::string(INDENT, ' ');
            width = 0;
        }
        oss << encoded;
        width += encoded.length();
    }

    return oss.str();
}

static void emit(std::ostream& os,
                 const std::string& label, const std::string& opcode = "",
                 const std::string& arguments = "", const std::string& comment = "") {
    os << std::left << std::setw(16) << label + " "
       << std::left << std::setw(8) << opcode + " "
       << std::left << std::setw(24) << arguments + " "
       << std::left << comment << std::endl;
}

static void emit_header(std::ostream& os, int pass) {
    os << "; Generated by z88dk-zx81dis" << std::endl;
    os << "; Pass: " << pass << std::endl;
    os << std::endl;
    emit(os, "", "SETFLOAT", "zx81");
    emit(os, "", "ORG", int16_to_hex(VERSN));
    os << std::endl;
}

static std::string align(unsigned int width, const std::string& text) {
    if (text.size() < width) {
        return text + std::string(width - text.size(), ' ');
    }
    else {
        return text;
    }
}

static void emit_charset(std::ostream& os) {
#define X(str, code, name) emit(os, "", "DEFC", align(16, #name) +" = "+int8_to_hex(code));
#include "zx81chars.def"
#undef X
    os << std::endl;

    emit(os, "", "DEFC", align(16, "SLOW_FLAG") + " = 0x40");
    emit(os, "", "DEFC", align(16, "FAST_FLAG") + " = 0x00");
    os << std::endl;
}

static void emit_sysvars(std::ostream& os, const Prog& prog) {
    size_t sysvars_index = 0;
    auto get_byte = [&](int def) -> int {
        if (sysvars_index < prog.sysvars.size()) {
            return prog.sysvars[sysvars_index++];
        }
        else {
            return def;
        }
    };
    auto get_word = [&](int def) -> int {
        uint8_t low = get_byte(static_cast<uint8_t>(def & 0xFF));
        uint8_t high = get_byte(static_cast<uint8_t>((def >> 8) & 0xFF));
        return static_cast<uint16_t>(low) | (static_cast<uint16_t>(high) << 8);
    };

    emit(os, "VERSN:", "DEFB", std::to_string(get_byte(0)));
    emit(os, "E_PPC:", "DEFW", std::to_string(get_word(0)));
    emit(os, "D_FILE:", "DEFW", "DISPLAY");
    sysvars_index += 2;
    emit(os, "DF_CC:", "DEFW", "DISPLAY+1");
    sysvars_index += 2;
    emit(os, "VARS:", "DEFW", "VARIABLES");
    sysvars_index += 2;
    emit(os, "DEST:", "DEFW", int16_to_hex(get_word(0)));
    emit(os, "E_LINE:", "DEFW", "WORKSPACE");
    sysvars_index += 2;

    int ch_add = get_word(0);
    if (ch_add == 0) {
        emit(os, "CH_ADD:", "DEFW", "WORKSPACE");
    }
    else {
        emit(os, "CH_ADD:", "DEFW", int16_to_hex(ch_add));
    }

    emit(os, "X_PTR:", "DEFW", int16_to_hex(get_word(0)));

    int stkbot = get_word(0);
    if (stkbot == 0) {
        emit(os, "STKBOT:", "DEFW", "WORKSPACE");
    }
    else {
        emit(os, "STKBOT:", "DEFW", int16_to_hex(stkbot));
    }

    int stkend = get_word(0);
    if (stkend == 0) {
        emit(os, "STKEND:", "DEFW", "WORKSPACE");
    }
    else {
        emit(os, "STKEND:", "DEFW", int16_to_hex(stkend));
    }

    emit(os, "BREG:", "DEFB", std::to_string(get_byte(0)));
    uint16_t mem = get_word(0x405D);
    emit(os, "MEM:", "DEFW",
         mem == 0x405D ? "MEMBOT" : int16_to_hex(mem));
    emit(os, "FREE1:", "DEFB", std::to_string(get_byte(0)));
    emit(os, "DF_SZ:", "DEFB", std::to_string(get_byte(2)));
    emit(os, "S_TOP:", "DEFW", std::to_string(get_word(0)));
    emit(os, "LAST_K:", "DEFW", int16_to_hex(get_word(0xFFFF)));
    emit(os, "DBOUNCE:", "DEFB", int8_to_hex(get_byte(0)));
    emit(os, "MARGIN:", "DEFB", std::to_string(get_byte(55)));

    // auto execute line
    if (prog.autostart) {
        emit(os, "NXTLIN:", "DEFW", "AUTOSTART_ADDR");
    }
    else {
        emit(os, "NXTLIN:", "DEFW", "DISPLAY");
    }
    sysvars_index += 2;

    emit(os, "OLDPPC:", "DEFW", std::to_string(get_word(0)));
    emit(os, "FLAGX:", "DEFB", int8_to_hex(get_byte(0)));
    emit(os, "STRLEN:", "DEFW", std::to_string(get_word(0)));
    emit(os, "T_ADDR:", "DEFW", int16_to_hex(get_word(0)));
    emit(os, "SEED:", "DEFW", int16_to_hex(get_word(0)));
    emit(os, "FRAMES:", "DEFW", int16_to_hex(get_word(0xFFFF)));
    emit(os, "COORDS:");
    emit(os, "COORDX:", "DEFB", std::to_string(get_byte(0)));
    emit(os, "COORDY:", "DEFB", std::to_string(get_byte(0)));
    emit(os, "PR_CC:", "DEFB", int8_to_hex(get_byte(0)));
    emit(os, "S_POSN:");
    emit(os, "S_POSNC:", "DEFB", std::to_string(get_byte(33)));
    emit(os, "S_POSNL:", "DEFB", std::to_string(get_byte(24)));

    // FAST/SLOW flag
    if (prog.fast) {
        emit(os, "CDFLAG:", "DEFB", "FAST_FLAG");
    }
    else {
        emit(os, "CDFLAG:", "DEFB", "SLOW_FLAG");
    }
    sysvars_index++;

    // printer buffer
    emit(os, "PRBUFF:");
    for (int i = 0; i < 32; i++) {
        emit(os, "", "DEFB", zx81_char_name(get_byte(CH_SP)));
    }
    emit(os, "", "DEFB", zx81_char_name(get_byte(CH_NL)));

    // calculator workspace
    emit(os, "MEMBOT:");
    for (int mem = 0; mem < 30 / 5; mem++) {
        std::array<uint8_t, 5> float_bytes{0};
        for (size_t i = 0; i < float_bytes.size(); i++) {
            float_bytes[i] = get_byte(0);
        }
        double float_value = zx81_to_float(float_bytes);
        emit(os, "MEM" + std::to_string(mem) + ":", "FLOAT",
             double_to_string(float_value));
    }

    emit(os, "FREE2:", "DEFW", int16_to_hex(get_word(0)));

    os << std::endl;
}

static void emit_prog(std::ostream& os, int pass, const Prog& prog,
                      std::unordered_map<std::string, int>& labels) {
    bool did_autostart_addr = false;

    emit(os, "PROG:");
    os << std::endl;
    for (size_t i = 0; i < prog.lines.size(); ++i) {
        auto& line = prog.lines[i];
        if (line.tokens.empty() ||
                line.tokens.front().type == TokenType::Hash) {
            continue;
        }

        // autostart
        if (prog.autostart && !did_autostart_addr) {
            if (line.line_num >= prog.autostart_line) {
                emit(os, "AUTOSTART_ADDR:");
                did_autostart_addr = true;
            }
        }

        // BASIC label
        if (!line.label.empty()) {
            emit(os, line.label + ":");
        }

        // line text as comment
        emit(os, "; " + std::to_string(line.line_num) + to_string(line.tokens));

        // line label, line number and size
        std::ostringstream oss;
        oss << std::setw(4) << std::setfill('0') << line.line_num;
        std::string line_label = "L" + oss.str();

        emit(os, "", "DDB", std::to_string(line.line_num));
        emit(os, "", "DEFW", line_label + "_END - " + line_label + "_START");
        emit(os, line_label + "_START:");

        // line tokens as DEFB
        // copy tokens and replace label references with addresses
        std::vector<Token> copy_tokens;
        copy_tokens.reserve(line.tokens.size());
        for (const auto& token : line.tokens) {
            Token copy_token = token;
            if (token.type == TokenType::LabelRefAddr) {
                auto it = labels.find(token.svalue);
                if (it == labels.end()) {
                    if (pass == 2) {
                        error("Undefined label: " + token.svalue);
                    }
                    copy_token.type = TokenType::Integer;
                    copy_token.ivalue = 0;
                    copy_token.text = "0";
                }
                else {
                    int addr = it->second;
                    copy_token.type = TokenType::Integer;
                    copy_token.ivalue = addr;
                    copy_token.text = std::to_string(addr);
                }
            }
            copy_tokens.push_back(copy_token);
        }

        // output tokens as DEFB
        for (auto& token : copy_tokens) {
            switch (token.type) {
            case TokenType::Float:
            case TokenType::Integer:
                emit(os, "", "DEFB",
                     string_to_zx81(token.text, /*check_keywords=*/false));
                emit(os, "", "DEFB", "_NUMBER");
                emit(os, "", "FLOAT", token.text);
                break;
            case TokenType::StringLiteral:
                emit(os, "", "DEFB", "_QUOTE");
                if (!token.svalue.empty()) {
                    emit(os, "", "DEFB",
                         string_to_zx81(token.svalue, /*check_keywords=*/false));
                }
                emit(os, "", "DEFB", "_QUOTE");
                break;
            default:
                emit(os, "", "DEFB", string_to_zx81(token.text, /*check_keywords=*/true));
                break;
            }
        }

        // skip #ASM directives
        while (i + 1 < prog.lines.size() &&
                prog.lines[i + 1].type == SourceType::BASIC &&
                !prog.lines[i + 1].tokens.empty() &&
                prog.lines[i + 1].tokens.front().type == TokenType::Hash) {
            i++;
        }

        // asm lines
        bool has_asm_block = false;
        while (i + 1 < prog.lines.size() &&
                prog.lines[i + 1].type == SourceType::ASM) {
            has_asm_block = true;

            const auto& asm_line = prog.lines[++i];
            std::ostringstream oss;
            for (const auto& token : asm_line.tokens) {
                oss << token.ws_before;
                switch (token.type) {
                case TokenType::CharConstant:
                    oss << string_to_zx81(token.svalue, /*check_keywords=*/false);
                    break;
                case TokenType::StringLiteral:
                    oss << string_to_zx81(token.svalue, /*check_keywords=*/false);
                    break;
                case TokenType::LabelRefAddr: {
                    auto it = labels.find(token.svalue);
                    if (it == labels.end()) {
                        if (pass == 2) {
                            error("Undefined label: " + token.svalue);
                        }
                        oss << "0";
                    }
                    else {
                        int addr = it->second;
                        oss << int16_to_hex(addr);
                    }
                    break;
                }
                default:
                    oss << token.text;
                    break;
                }
            }
            emit(os, oss.str());
        }

        if (has_asm_block) {
            os << std::endl;
        }

        // end of line
        emit(os, "", "DEFB", "_NL");

        os << std::endl;
        emit(os, line_label + "_END:");
        os << std::endl;
    }

    if (!did_autostart_addr) {
        emit(os, "AUTOSTART_ADDR:");
        did_autostart_addr = true;
    }
}

static void emit_display(std::ostream& os, const Prog& prog) {
    emit(os, "DISPLAY:", "DEFB", "_NL");

    for (size_t i = 0; i < 24; ++i) {
        std::string text = (i < prog.dfile.size()) ? prog.dfile[i] : "";
        if (prog.dfile_colapsed) {
            text = str_trim(text);
        }
        else {
            text = fixed_width_string(text, 32);
        }

        std::ostringstream oss;
        oss << std::setw(2) << std::setfill('0') << i;
        emit(os, "DSPLY" + oss.str() + ":", "DEFB",
             string_to_zx81(text,
                            /*check_keywords=*/false));
        emit(os, "", "DEFB", "_NL");
    }

    os << std::endl;
}

static void emit_vars(std::ostream& os, const Prog& prog) {
    emit(os, "VARIABLES:");
    os << std::endl;

    for (auto& var : prog.variables) {
        if (var.is_loop_var) {
            // loop variable

            // header
            os << "; Variable: " << var.name << " = "
               << var.nvalues[0] << " TO "
               << var.limit << " STEP "
               << var.step << " GOTO "
               << var.line_num << std::endl;

            // convert variable name to ZX81 bytes
            const char* p = var.name.c_str();
            uint8_t code = 0;
            std::string encoded;

            // 111-letter
            if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                error("Invalid variable name: " + var.name);
                return;
            }
            encoded = zx81_char_name(code);
            emit(os, "", "DEFB", "(" + encoded + " & 0x3F) | 0xE0");

            // put values
            emit(os, "", "FLOAT", double_to_string(var.nvalues[0]));
            emit(os, "", "FLOAT", double_to_string(var.limit));
            emit(os, "", "FLOAT", double_to_string(var.step));
            emit(os, "", "DEFW", std::to_string(var.line_num));
            os << std::endl;;

        }
        else if (var.is_string_var) {
            if (var.is_array_var) {
                // string array variable

                // header
                size_t num_values = 1;
                os << "; Array: " << var.name << "(";
                bool first = true;
                for (auto dim : var.dims) {
                    if (!first) {
                        os << ",";
                    }
                    first = false;

                    os << dim;
                    num_values *= dim;
                }
                os << ") = (";
                size_t last_dimension = var.dims.back();
                num_values /= last_dimension;
                std::vector<std::string> trimmed_strs;
                trimmed_strs.reserve(num_values);
                for (size_t i = 0; i < num_values; ++i) {
                    if (i > 0) {
                        os << ",";
                    }
                    std::string svalue = (i < var.svalues.size()) ? var.svalues[i] : "";
                    svalue = fixed_width_string(svalue, last_dimension);
                    trimmed_strs.push_back(svalue);
                    os << "\"" << svalue << "\"";
                }
                os << ")" << std::endl;

                // convert variable name to ZX81 bytes
                const char* p = var.name.c_str();
                uint8_t code = 0;
                std::string encoded;
                // 110-letter
                if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                    error("Invalid variable name: " + var.name);
                    return;
                }
                encoded = zx81_char_name(code);
                emit(os, "", "DEFB", "(" + encoded + " & 0x1F) | 0xC0");

                // dimensions
                emit(os, "", "DEFW", "1 + "
                     "2 * " + std::to_string(var.dims.size()) + " + " +
                     std::to_string(last_dimension) + " * " + std::to_string(num_values));

                emit(os, "", "DEFB", std::to_string(var.dims.size() & 0xff));

                for (auto dim : var.dims) {
                    emit(os, "", "DEFW", std::to_string(dim));
                }

                for (auto& str : trimmed_strs) {
                    emit(os, "", "DEFB", string_to_zx81(str,/*check_keywords=*/false));
                }

                os << std::endl;;
            }
            else {
                // string scalar variable
                os << "; Variable: " << var.name << " = \""
                   << var.svalues[0] << "\"" << std::endl;

                const char* p = var.name.c_str();
                uint8_t code = 0;
                std::string encoded;
                // 010-letter
                if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                    error("Invalid variable name: " + var.name);
                    return;
                }
                encoded = zx81_char_name(code);
                emit(os, "", "DEFB", "(" + encoded + " & 0x1F) | 0x40");

                // size field
                std::string name_without_dollar = var.name.substr(0, var.name.size() - 1);
                std::string label_radix = "VAR_" + name_without_dollar;
                emit(os, "", "DEFW", label_radix + "_END - " + label_radix + "_START");
                emit(os, label_radix + "_START:");

                // emit string value as ZX81 bytes
                if (!var.svalues.empty()) {
                    emit(os, "", "DEFB", string_to_zx81(var.svalues[0],/*check_keywords=*/false));
                }

                emit(os, label_radix + "_END:");
                os << std::endl;;
            }
        }
        else {
            if (var.is_array_var) {
                // numeric array variable

                // header
                size_t num_values = 1;
                os << "; Array: " << var.name << "(";
                bool first = true;
                for (auto dim : var.dims) {
                    if (!first) {
                        os << ",";
                    }
                    first = false;

                    os << dim;
                    num_values *= dim;
                }
                os << ") = (";
                for (size_t i = 0; i < num_values; ++i) {
                    if (i > 0) {
                        os << ",";
                    }
                    double value = (i < var.nvalues.size()) ? var.nvalues[i] : 0.0;
                    os << value;
                }
                os << ")" << std::endl;

                // convert variable name to ZX81 bytes
                const char* p = var.name.c_str();
                uint8_t code = 0;
                std::string encoded;
                // 100-letter
                if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                    error("Invalid variable name: '" + var.name + "'");
                    return;
                }
                encoded = zx81_char_name(code);
                emit(os, "", "DEFB", "(" + encoded + " & 0x1F) | 0x80");

                // dimensions
                emit(os, "", "DEFW", "1 + "
                     "2 * " + std::to_string(var.dims.size()) + " + " +
                     "5 * " + std::to_string(num_values));

                emit(os, "", "DEFB", std::to_string(var.dims.size() & 0xff));

                for (auto dim : var.dims) {
                    emit(os, "", "DEFW", std::to_string(dim));
                }

                for (size_t i = 0; i < num_values; ++i) {
                    double value = (i < var.nvalues.size()) ? var.nvalues[i] : 0.0;
                    emit(os, "", "FLOAT", double_to_string(value));
                }

                os << std::endl;;
            }
            else {
                // numeric scalar variable
                os << "; Variable: " << var.name << " = "
                   << double_to_string(var.nvalues[0]) << std::endl;

                const char* p = var.name.c_str();
                uint8_t code = 0;
                std::string encoded;
                if (var.name.size() == 1) {
                    // 011-letter
                    if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                        error("Invalid variable name: " + var.name);
                        return;
                    }
                    encoded = zx81_char_name(code);
                    emit(os, "", "DEFB", "(" + encoded + " & 0x3F) | 0x60");
                }
                else {
                    // 101-letter, 001-letter, 101-letter
                    if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                        error("Invalid variable name: " + var.name);
                        return;
                    }
                    encoded = zx81_char_name(code);
                    emit(os, "", "DEFB", "(" + encoded + " & 0x3F) | 0xA0");

                    for (size_t i = 1; i + 1 < var.name.size(); i++) {
                        if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                            error("Invalid variable name: " + var.name);
                            return;
                        }
                        encoded = zx81_char_name(code);
                        emit(os, "", "DEFB", "(" + encoded + " & 0x3F)");
                    }

                    if (!encode_zx81_char(p, /*check_keywords=*/false, code, SourceLoc())) {
                        error("Invalid variable name: " + var.name);
                        return;
                    }
                    encoded = zx81_char_name(code);
                    emit(os, "", "DEFB", "(" + encoded + " & 0x3F) | 0x80");
                }

                // put value
                emit(os, "", "FLOAT", double_to_string(var.nvalues[0]));
                os << std::endl;;
            }
        }
    }

    os << std::endl;
    emit(os, "", "DEFB", "0x80");
    emit(os, "WORKSPACE:");
    os << std::endl;
}

// some tapes have a trailer newline after E_LINE
static void emit_trailer(std::ostream& os, const Prog& prog) {
    for (auto byte : prog.trailer) {
        emit(os, "", "DEFB", zx81_char_name(byte));
    }
    os << std::endl;
}

static void emit_asm(int pass, const std::string& asm_filename,
                     const Prog& prog,
                     std::unordered_map<std::string, int>& labels) {
    std::ofstream ofs(asm_filename, std::ios::binary);
    if (!ofs) {
        fatal("Failed to open output file: " + asm_filename);
    }

    emit_header(ofs, pass);
    emit_charset(ofs);
    emit_sysvars(ofs, prog);
    emit_prog(ofs, pass, prog, labels);
    emit_display(ofs, prog);
    emit_vars(ofs, prog);
    emit_trailer(ofs, prog);
}

static void assemble(const std::string& asm_filename) {
    std::string p_filename = replace_extension(asm_filename, ".p");
    std::string z80asm = "z88dk-z80asm -m -b -o" + p_filename + " " + asm_filename;
    std::cout << z80asm << std::endl;
    if (system(z80asm.c_str()) != 0) {
        exit(EXIT_FAILURE);
    }
}

static bool get_labels(const std::string& map_filename,
                       std::unordered_map<std::string, int>& labels) {
    bool symbols_changed = false;
    std::ifstream ifs(map_filename, std::ios::binary);
    if (!ifs) {
        fatal("Failed to open input file: " + map_filename);
    }

    std::string text;
    while (std::getline(ifs, text)) {
        // parse SYMBOL = $HHHH
        const char* p = text.c_str();
        while (isspace(*p)) {
            p++;
        }
        const char* sname = p;
        while (*p == '_' || isalnum(*p)) {
            p++;
        }
        const char* ename = p;
        std::string symbol(sname, ename - sname);

        while (isspace(*p)) {
            p++;
        }
        if (*p == '=') {
            p++;
        }
        while (isspace(*p)) {
            p++;
        }
        if (*p == '$') {
            p++;
        }
        const char* saddr = p;
        while (isxdigit(*p)) {
            p++;
        }
        const char* eaddr = p;
        std::string hexaddr(saddr, eaddr - saddr);
        int addr = std::stoul(hexaddr, nullptr, 16);

        // check symbol table
        auto it = labels.find(symbol);
        if (it == labels.end()) {
            // new symbol
            labels[symbol] = addr;
            symbols_changed = true;
        }
        else {
            int old_addr = it->second;
            if (old_addr != addr) {
                // symbol changed because output did not stabilize yet
                labels[symbol] = addr;
                symbols_changed = true;
            }
        }
    }

    return symbols_changed;
}

void ass_emit_p(const std::string& p_filename, const Prog& prog) {
    std::string asm_filename = replace_extension(p_filename, ".asm");
    std::string map_filename = replace_extension(p_filename, ".map");

    std::unordered_map<std::string, int> labels;
    for (int pass = 1; pass <= 2; pass++) {
        emit_asm(pass, asm_filename, prog, labels);
        if (get_error_count() > 0) {
            exit_error_status();
        }
        assemble(asm_filename);
        if (get_error_count() > 0) {
            exit_error_status();
        }
        if (get_labels(map_filename, labels)) {
            pass = 0;   // some labels changed since last run; run again
        }
    }
}
