/* Generated by re2c 4.4 */
//-----------------------------------------------------------------------------
// zx81bas
// Copyright (C) Paulo Custodio, 2023-2026
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#include "errors.h"
#include "lexer.h"
#include "utils.h"
#include "zx81chars.h"
#include <cctype>
#include <string>
#include <vector>



// Remove underscores
static double parse_float_from_chars(const std::string& s) {
    std::string t;
    t.reserve(s.size());
    for (char c : s) {
        if (c != '_') {
            t.push_back(c);
        }
    }
    return std::stod(t);
}

// Remove underscores
static int parse_int_from_chars(const std::string& s, int base) {
    std::string t;
    t.reserve(s.size());
    for (char c : s) {
        if (c != '_') {
            t.push_back(c);
        }
    }
    return std::stoul(t, nullptr, base);
}

bool tokenize_line(const std::string& text, SourceType source_type,
                   const SourceLoc& loc,
                   std::vector<Token>& tokens) {
    const char* p = text.c_str();
    const char* limit = p + text.size();
    const char* marker = nullptr;

    auto check_trailing_char = [&]() -> bool {
        if (isalnum(*p) || *p == '_') {
            error(loc, "Invalid character '" + std::string(1, *p) + "'");
            return false;
        }
        return true;
    };

    while (*p) {
        Token token;
collect_token:
        const char* start = p;
        token.pos = p - text.c_str();


        {
            char yych;
            unsigned int yyaccept = 0;
            yych = *p;
            switch (yych) {
            case '\t':
            case '\n':
            case '\v':
            case '\f':
            case '\r':
            case ' ':
                goto yy2;
            case '!':
                goto yy4;
            case '"':
                goto yy6;
            case '#':
                goto yy7;
            case '$':
                goto yy9;
            case '%':
                goto yy11;
            case '&':
                goto yy13;
            case '\'':
                goto yy15;
            case '(':
                goto yy16;
            case ')':
                goto yy17;
            case '*':
                goto yy18;
            case '+':
                goto yy20;
            case ',':
                goto yy21;
            case '-':
                goto yy22;
            case '.':
                goto yy23;
            case '/':
                goto yy25;
            case '0':
                goto yy27;
            case '1':
                goto yy29;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case ':':
                goto yy32;
            case ';':
                goto yy33;
            case '<':
                goto yy34;
            case '=':
                goto yy36;
            case '>':
                goto yy38;
            case '?':
                goto yy40;
            case '@':
                goto yy41;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy43;
            case '[':
                goto yy45;
            case '\\':
                goto yy46;
            case ']':
                goto yy48;
            case '^':
                goto yy49;
            case '{':
                goto yy51;
            case '|':
                goto yy52;
            case '}':
                goto yy54;
            case '~':
                goto yy55;
            default:
                if (limit <= p) {
                    goto yy110;
                }
                goto yy1;
            }
yy1:
            ++p;
            {
                error(loc, "Unexpected character: '" + std::string(1, *(p - 1)) + "'");
                break;
            }
yy2:
            yych = *++p;
            switch (yych) {
            case '\t':
            case '\n':
            case '\v':
            case '\f':
            case '\r':
            case ' ':
                goto yy2;
            default:
                goto yy3;
            }
yy3: {
                token.ws_before += std::string(start, p);
                goto collect_token;
            }
yy4:
            yych = *++p;
            switch (yych) {
            case '=':
                goto yy56;
            default:
                goto yy5;
            }
yy5: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy6:
            ++p;
            {
                // String literal
                std::vector<uint8_t> bytes;
                if (!encode_zx81_string(p, '"', bytes, loc)) {
                    break;
                }
                p++; // skip closing quote
                token.text = std::string(start, p);
                token.svalue = std::string(start + 1, p - 1);
                token.type = TokenType::StringLiteral;
                goto push_token;
            }
yy7:
            yych = *++p;
            switch (yych) {
            case '#':
                goto yy57;
            default:
                goto yy8;
            }
yy8: {
                token.type = TokenType::Hash;
                token.text = std::string(start, p);
                goto push_token;
            }
yy9:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy58;
            default:
                goto yy10;
            }
yy10: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy11:
            yyaccept = 0;
            yych = *(marker = ++p);
            switch (yych) {
            case '"':
                goto yy60;
            case '0':
            case '1':
                goto yy62;
            default:
                goto yy12;
            }
yy12: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy13:
            yych = *++p;
            switch (yych) {
            case '&':
                goto yy64;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy65;
            default:
                goto yy14;
            }
yy14: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy15:
            ++p;
            {
                if (source_type == SourceType::BASIC) {
                    break; // ignore the rest of the line
                }
                else {
                    // Char constant
                    std::vector<uint8_t> bytes;
                    if (!encode_zx81_string(p, '\'', bytes, loc)) {
                        break;
                    }
                    p++; // skip closing quote
                    if (bytes.size() != 1) {
                        error(loc, "Char constant must be a single character");
                        break;
                    }
                    token.text = std::string(start, p);
                    token.svalue = std::string(start + 1, p - 1);
                    token.type = TokenType::CharConstant;
                    goto push_token;
                }
            }
yy16:
            ++p;
            {
                token.type = TokenType::LParen;
                token.text = std::string(start, p);
                goto push_token;
            }
yy17:
            ++p;
            {
                token.type = TokenType::RParen;
                token.text = std::string(start, p);
                goto push_token;
            }
yy18:
            yych = *++p;
            switch (yych) {
            case '*':
                goto yy67;
            default:
                goto yy19;
            }
yy19: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy20:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy21:
            ++p;
            {
                token.type = TokenType::Comma;
                token.text = std::string(start, p);
                goto push_token;
            }
yy22:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy23:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy68;
            default:
                goto yy24;
            }
yy24: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy25:
            yych = *++p;
            switch (yych) {
            case '/':
                goto yy71;
            default:
                goto yy26;
            }
yy26: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy27:
            yyaccept = 1;
            yych = *(marker = ++p);
            switch (yych) {
            case 0x00:
                goto yy28;
            case 'B':
            case 'b':
                goto yy74;
            case 'X':
            case 'x':
                goto yy78;
            default:
                goto yy30;
            }
yy28: {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text, 10);
                goto push_token;
            }
yy29:
            yyaccept = 1;
            yych = *(marker = ++p);
yy30:
            switch (yych) {
            case '.':
                goto yy72;
            case '0':
            case '1':
                goto yy29;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'C':
            case 'E':
            case 'F':
            case 'a':
            case 'c':
            case 'e':
            case 'f':
                goto yy73;
            case 'B':
            case 'b':
                goto yy80;
            case 'D':
            case 'd':
                goto yy76;
            case 'H':
            case 'h':
                goto yy77;
            case '_':
                goto yy79;
            default:
                goto yy28;
            }
yy31:
            yyaccept = 1;
            yych = *(marker = ++p);
            switch (yych) {
            case '.':
                goto yy72;
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'B':
            case 'C':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'e':
            case 'f':
                goto yy73;
            case 'D':
            case 'd':
                goto yy76;
            case 'H':
            case 'h':
                goto yy77;
            case '_':
                goto yy81;
            default:
                goto yy28;
            }
yy32:
            ++p;
            {
                token.type = TokenType::Colon;
                token.text = std::string(start, p);
                goto push_token;
            }
yy33:
            ++p;
            {
                if (source_type == SourceType::BASIC) {
                    token.type = TokenType::Punctuation;
                    token.text = std::string(start, p);
                    goto push_token;
                }
                else {
                    break; // ignore the rest of the line
                }
            }
yy34:
            yych = *++p;
            switch (yych) {
            case '<':
                goto yy82;
            case '=':
                goto yy83;
            case '>':
                goto yy84;
            default:
                goto yy35;
            }
yy35: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy36:
            yych = *++p;
            switch (yych) {
            case '=':
                goto yy85;
            default:
                goto yy37;
            }
yy37: {
                token.type = TokenType::Equal;
                token.text = std::string(start, p);
                goto push_token;
            }
yy38:
            yych = *++p;
            switch (yych) {
            case '=':
                goto yy86;
            case '>':
                goto yy87;
            default:
                goto yy39;
            }
yy39: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy40:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy41:
            yyaccept = 2;
            yych = *(marker = ++p);
            switch (yych) {
            case '"':
                goto yy60;
            case '0':
            case '1':
                goto yy62;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy88;
            default:
                goto yy42;
            }
yy42: {
                token.type = TokenType::At;
                token.text = std::string(start, p);
                goto push_token;
            }
yy43:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy43;
            default:
                goto yy44;
            }
yy44: {
                if (source_type == SourceType::BASIC && *p == '$') {
                    ++p; // include trailing $ in identifier
                }
                token.type = TokenType::Identifier;
                token.text = str_toupper(std::string(start, p));    // BASIC is case insensitive
                token.keyword = lookup_keyword(token.text);
                goto push_token;
            }
yy45:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy46:
            yyaccept = 3;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy90;
            default:
                goto yy47;
            }
yy47: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy48:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy49:
            yych = *++p;
            switch (yych) {
            case '^':
                goto yy91;
            default:
                goto yy50;
            }
yy50: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy51:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy52:
            yych = *++p;
            switch (yych) {
            case '|':
                goto yy92;
            default:
                goto yy53;
            }
yy53: {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy54:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy55:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy56:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy57:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy58:
            yyaccept = 4;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy58;
            case '_':
                goto yy93;
            default:
                goto yy59;
            }
yy59: {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text.substr(1), 16);
                goto push_token;
            }
yy60:
            yych = *++p;
            switch (yych) {
            case '"':
                goto yy94;
            case '#':
            case '-':
                goto yy60;
            default:
                goto yy61;
            }
yy61:
            p = marker;
            switch (yyaccept) {
            case 0:
                goto yy12;
            case 1:
                goto yy28;
            case 2:
                goto yy42;
            case 3:
                goto yy47;
            case 4:
                goto yy59;
            case 5:
                goto yy63;
            case 6:
                goto yy70;
            case 7:
                goto yy75;
            case 8:
                goto yy101;
            default:
                goto yy103;
            }
yy62:
            yyaccept = 5;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
                goto yy62;
            case '_':
                goto yy95;
            default:
                goto yy63;
            }
yy63: {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text.substr(1), 2);
                goto push_token;
            }
yy64:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy65:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy65;
            default:
                goto yy66;
            }
yy66: {
                token.type = TokenType::LabelRefAddr;
                token.text = str_toupper(std::string(start, p));    // BASIC is case insensitive
                token.svalue = str_toupper(std::string(start + 1, p));
                goto push_token;
            }
yy67:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy68:
            yyaccept = 6;
            yych = *(marker = ++p);
yy69:
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy68;
            case 'E':
            case 'e':
                goto yy96;
            case '_':
                goto yy97;
            default:
                goto yy70;
            }
yy70: {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Float;
                token.text = std::string(start, p);
                token.nvalue = parse_float_from_chars(token.text);
                goto push_token;
            }
yy71:
            ++p;
            {
                break; // ignore the rest of the line
            }
yy72:
            yyaccept = 6;
            yych = *(marker = ++p);
            switch (yych) {
            case 0x00:
            case '_':
                goto yy70;
            default:
                goto yy69;
            }
yy73:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case 'H':
            case 'h':
                goto yy77;
            case '_':
                goto yy98;
            default:
                goto yy61;
            }
yy74:
            yyaccept = 7;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'H':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'h':
                goto yy100;
            case '_':
                goto yy98;
            default:
                goto yy75;
            }
yy75: {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text, 2);
                goto push_token;
            }
yy76:
            yyaccept = 1;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case 'H':
            case 'h':
                goto yy77;
            case '_':
                goto yy98;
            default:
                goto yy28;
            }
yy77:
            ++p;
            {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text, 16);
                goto push_token;
            }
yy78:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy102;
            default:
                goto yy61;
            }
yy79:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
                goto yy29;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case '_':
                goto yy79;
            default:
                goto yy61;
            }
yy80:
            yyaccept = 7;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case 'H':
            case 'h':
                goto yy77;
            case '_':
                goto yy98;
            default:
                goto yy75;
            }
yy81:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy31;
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case '_':
                goto yy81;
            default:
                goto yy61;
            }
yy82:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy83:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy84:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy85:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy86:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy87:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy88:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
                goto yy88;
            default:
                goto yy89;
            }
yy89: {
                token.type = TokenType::LabelRefLine;
                token.text = str_toupper(std::string(start, p));    // BASIC is case insensitive
                token.svalue = str_toupper(std::string(start + 1, p));
                goto push_token;
            }
yy90:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy104;
            default:
                goto yy61;
            }
yy91:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy92:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                goto push_token;
            }
yy93:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy58;
            case '_':
                goto yy93;
            default:
                goto yy61;
            }
yy94:
            ++p;
            {
                int value = 0;
                for (const char* i = start + 2; i < p - 1; ++i) {
                    value *= 2;
                    if (*i == '#') {
                        ++value;
                    }
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = value;
                goto push_token;
            }
yy95:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
                goto yy62;
            case '_':
                goto yy95;
            default:
                goto yy61;
            }
yy96:
            yych = *++p;
            switch (yych) {
            case '+':
            case '-':
                goto yy105;
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy106;
            default:
                goto yy61;
            }
yy97:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy68;
            case '_':
                goto yy97;
            default:
                goto yy61;
            }
yy98:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case '_':
                goto yy98;
            default:
                goto yy61;
            }
yy99:
            yyaccept = 8;
            yych = *(marker = ++p);
yy100:
            switch (yych) {
            case '0':
            case '1':
                goto yy99;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case 'H':
            case 'h':
                goto yy77;
            case '_':
                goto yy107;
            default:
                goto yy101;
            }
yy101: {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text.substr(2), 2);
                goto push_token;
            }
yy102:
            yyaccept = 9;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy102;
            case '_':
                goto yy108;
            default:
                goto yy103;
            }
yy103: {
                if (!check_trailing_char()) {
                    break;
                }
                token.type = TokenType::Integer;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text.substr(2), 16);
                goto push_token;
            }
yy104:
            ++p;
            {
                token.type = TokenType::Punctuation;
                token.text = std::string(start, p);
                token.ivalue = parse_int_from_chars(token.text.substr(1), 16);
                goto push_token;
            }
yy105:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy106;
            default:
                goto yy61;
            }
yy106:
            yyaccept = 6;
            yych = *(marker = ++p);
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy106;
            case '_':
                goto yy109;
            default:
                goto yy70;
            }
yy107:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
                goto yy99;
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy73;
            case '_':
                goto yy107;
            default:
                goto yy61;
            }
yy108:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
                goto yy102;
            case '_':
                goto yy108;
            default:
                goto yy61;
            }
yy109:
            yych = *++p;
            switch (yych) {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
                goto yy106;
            case '_':
                goto yy109;
            default:
                goto yy61;
            }
yy110: {
                break;
            }
        }

push_token:
        tokens.push_back(token);
    }

    return get_error_count() == 0;
}
