; Generated by z88dk-zx81dis
; Pass: 2

                SETFLOAT zx81                    
                ORG     0x4009                  

                DEFC    _WWWW            = 0x00 
                DEFC    _BWWW            = 0x01 
                DEFC    _WBWW            = 0x02 
                DEFC    _BBWW            = 0x03 
                DEFC    _WWBW            = 0x04 
                DEFC    _BWBW            = 0x05 
                DEFC    _WBBW            = 0x06 
                DEFC    _BBBW            = 0x07 
                DEFC    _GGGG            = 0x08 
                DEFC    _WWGG            = 0x09 
                DEFC    _GGWW            = 0x0A 
                DEFC    _BBBB            = 0x80 
                DEFC    _WBBB            = 0x81 
                DEFC    _BWBB            = 0x82 
                DEFC    _WWBB            = 0x83 
                DEFC    _BBWB            = 0x84 
                DEFC    _WBWB            = 0x85 
                DEFC    _BWWB            = 0x86 
                DEFC    _WWWB            = 0x87 
                DEFC    _INV_GGGG        = 0x88 
                DEFC    _BBGG            = 0x89 
                DEFC    _GGBB            = 0x8A 
                DEFC    _SP              = 0x00 
                DEFC    _INV_SP          = 0x80 
                DEFC    _NL              = 0x76 
                DEFC    _NUMBER          = 0x7E 
                DEFC    _QUOTE           = 0x0B 
                DEFC    _DOLLAR          = 0x0D 
                DEFC    _COLON           = 0x0E 
                DEFC    _QUESTION        = 0x0F 
                DEFC    _LPAREN          = 0x10 
                DEFC    _RPAREN          = 0x11 
                DEFC    _GT              = 0x12 
                DEFC    _LT              = 0x13 
                DEFC    _EQ              = 0x14 
                DEFC    _PLUS            = 0x15 
                DEFC    _MINUS           = 0x16 
                DEFC    _MULT            = 0x17 
                DEFC    _DIV             = 0x18 
                DEFC    _SEMICOLON       = 0x19 
                DEFC    _COMMA           = 0x1A 
                DEFC    _DOT             = 0x1B 
                DEFC    _0               = 0x1C 
                DEFC    _1               = 0x1D 
                DEFC    _2               = 0x1E 
                DEFC    _3               = 0x1F 
                DEFC    _4               = 0x20 
                DEFC    _5               = 0x21 
                DEFC    _6               = 0x22 
                DEFC    _7               = 0x23 
                DEFC    _8               = 0x24 
                DEFC    _9               = 0x25 
                DEFC    _A               = 0x26 
                DEFC    _B               = 0x27 
                DEFC    _C               = 0x28 
                DEFC    _D               = 0x29 
                DEFC    _E               = 0x2A 
                DEFC    _F               = 0x2B 
                DEFC    _G               = 0x2C 
                DEFC    _H               = 0x2D 
                DEFC    _I               = 0x2E 
                DEFC    _J               = 0x2F 
                DEFC    _K               = 0x30 
                DEFC    _L               = 0x31 
                DEFC    _M               = 0x32 
                DEFC    _N               = 0x33 
                DEFC    _O               = 0x34 
                DEFC    _P               = 0x35 
                DEFC    _Q               = 0x36 
                DEFC    _R               = 0x37 
                DEFC    _S               = 0x38 
                DEFC    _T               = 0x39 
                DEFC    _U               = 0x3A 
                DEFC    _V               = 0x3B 
                DEFC    _W               = 0x3C 
                DEFC    _X               = 0x3D 
                DEFC    _Y               = 0x3E 
                DEFC    _Z               = 0x3F 
                DEFC    _INV_QUOTE       = 0x8B 
                DEFC    _INV_DOLLAR      = 0x8D 
                DEFC    _INV_COLON       = 0x8E 
                DEFC    _INV_QUESTION    = 0x8F 
                DEFC    _INV_LPAREN      = 0x90 
                DEFC    _INV_RPAREN      = 0x91 
                DEFC    _INV_GT          = 0x92 
                DEFC    _INV_LT          = 0x93 
                DEFC    _INV_EQ          = 0x94 
                DEFC    _INV_PLUS        = 0x95 
                DEFC    _INV_MINUS       = 0x96 
                DEFC    _INV_MULT        = 0x97 
                DEFC    _INV_DIV         = 0x98 
                DEFC    _INV_SEMICOLON   = 0x99 
                DEFC    _INV_COMMA       = 0x9A 
                DEFC    _INV_DOT         = 0x9B 
                DEFC    _INV_0           = 0x9C 
                DEFC    _INV_1           = 0x9D 
                DEFC    _INV_2           = 0x9E 
                DEFC    _INV_3           = 0x9F 
                DEFC    _INV_4           = 0xA0 
                DEFC    _INV_5           = 0xA1 
                DEFC    _INV_6           = 0xA2 
                DEFC    _INV_7           = 0xA3 
                DEFC    _INV_8           = 0xA4 
                DEFC    _INV_9           = 0xA5 
                DEFC    _INV_A           = 0xA6 
                DEFC    _INV_B           = 0xA7 
                DEFC    _INV_C           = 0xA8 
                DEFC    _INV_D           = 0xA9 
                DEFC    _INV_E           = 0xAA 
                DEFC    _INV_F           = 0xAB 
                DEFC    _INV_G           = 0xAC 
                DEFC    _INV_H           = 0xAD 
                DEFC    _INV_I           = 0xAE 
                DEFC    _INV_J           = 0xAF 
                DEFC    _INV_K           = 0xB0 
                DEFC    _INV_L           = 0xB1 
                DEFC    _INV_M           = 0xB2 
                DEFC    _INV_N           = 0xB3 
                DEFC    _INV_O           = 0xB4 
                DEFC    _INV_P           = 0xB5 
                DEFC    _INV_Q           = 0xB6 
                DEFC    _INV_R           = 0xB7 
                DEFC    _INV_S           = 0xB8 
                DEFC    _INV_T           = 0xB9 
                DEFC    _INV_U           = 0xBA 
                DEFC    _INV_V           = 0xBB 
                DEFC    _INV_W           = 0xBC 
                DEFC    _INV_X           = 0xBD 
                DEFC    _INV_Y           = 0xBE 
                DEFC    _INV_Z           = 0xBF 
                DEFC    _DOUBLE_QUOTE    = 0xC0 
                DEFC    _POWER           = 0xD8 
                DEFC    _LE              = 0xDB 
                DEFC    _GE              = 0xDC 
                DEFC    _NE              = 0xDD 
                DEFC    _RND             = 0x40 
                DEFC    _INKEY_DOLLAR    = 0x41 
                DEFC    _PI              = 0x42 
                DEFC    _AT              = 0xC1 
                DEFC    _TAB             = 0xC2 
                DEFC    _CODE            = 0xC4 
                DEFC    _VAL             = 0xC5 
                DEFC    _LEN             = 0xC6 
                DEFC    _SIN             = 0xC7 
                DEFC    _COS             = 0xC8 
                DEFC    _TAN             = 0xC9 
                DEFC    _ASN             = 0xCA 
                DEFC    _ACS             = 0xCB 
                DEFC    _ATN             = 0xCC 
                DEFC    _LN              = 0xCD 
                DEFC    _EXP             = 0xCE 
                DEFC    _INT             = 0xCF 
                DEFC    _SQR             = 0xD0 
                DEFC    _SGN             = 0xD1 
                DEFC    _ABS             = 0xD2 
                DEFC    _PEEK            = 0xD3 
                DEFC    _USR             = 0xD4 
                DEFC    _STR_DOLLAR      = 0xD5 
                DEFC    _CHR_DOLLAR      = 0xD6 
                DEFC    _NOT             = 0xD7 
                DEFC    _OR              = 0xD9 
                DEFC    _AND             = 0xDA 
                DEFC    _THEN            = 0xDE 
                DEFC    _TO              = 0xDF 
                DEFC    _STEP            = 0xE0 
                DEFC    _LPRINT          = 0xE1 
                DEFC    _LLIST           = 0xE2 
                DEFC    _STOP            = 0xE3 
                DEFC    _SLOW            = 0xE4 
                DEFC    _FAST            = 0xE5 
                DEFC    _NEW             = 0xE6 
                DEFC    _SCROLL          = 0xE7 
                DEFC    _CONT            = 0xE8 
                DEFC    _DIM             = 0xE9 
                DEFC    _REM             = 0xEA 
                DEFC    _FOR             = 0xEB 
                DEFC    _GOTO            = 0xEC 
                DEFC    _GOSUB           = 0xED 
                DEFC    _INPUT           = 0xEE 
                DEFC    _LOAD            = 0xEF 
                DEFC    _LIST            = 0xF0 
                DEFC    _LET             = 0xF1 
                DEFC    _PAUSE           = 0xF2 
                DEFC    _NEXT            = 0xF3 
                DEFC    _POKE            = 0xF4 
                DEFC    _PRINT           = 0xF5 
                DEFC    _PLOT            = 0xF6 
                DEFC    _RUN             = 0xF7 
                DEFC    _SAVE            = 0xF8 
                DEFC    _RAND            = 0xF9 
                DEFC    _IF              = 0xFA 
                DEFC    _CLS             = 0xFB 
                DEFC    _UNPLOT          = 0xFC 
                DEFC    _CLEAR           = 0xFD 
                DEFC    _RETURN          = 0xFE 
                DEFC    _COPY            = 0xFF 

                DEFC    SLOW_FLAG        = 0x40 
                DEFC    FAST_FLAG        = 0x00 

VERSN:          DEFB    0                       
E_PPC:          DEFW    0                       
D_FILE:         DEFW    DISPLAY                 
DF_CC:          DEFW    DISPLAY+1               
VARS:           DEFW    VARIABLES               
DEST:           DEFW    0x0000                  
E_LINE:         DEFW    WORKSPACE               
CH_ADD:         DEFW    0x4136                  
X_PTR:          DEFW    0x0000                  
STKBOT:         DEFW    0x4136                  
STKEND:         DEFW    0x4136                  
BREG:           DEFB    0                       
MEM:            DEFW    MEMBOT                  
FREE1:          DEFB    0                       
DF_SZ:          DEFB    2                       
S_TOP:          DEFW    0                       
LAST_K:         DEFW    0xFFFF                  
DBOUNCE:        DEFB    0x00                    
MARGIN:         DEFB    55                      
NXTLIN:         DEFW    DISPLAY                 
OLDPPC:         DEFW    0                       
FLAGX:          DEFB    0x00                    
STRLEN:         DEFW    0                       
T_ADDR:         DEFW    0x0000                  
SEED:           DEFW    0x0000                  
FRAMES:         DEFW    0xFFFF                  
COORDS:                                         
COORDX:         DEFB    0                       
COORDY:         DEFB    0                       
PR_CC:          DEFB    0x3C                    
S_POSN:                                         
S_POSNC:        DEFB    33                      
S_POSNL:        DEFB    24                      
CDFLAG:         DEFB    SLOW_FLAG               
PRBUFF:                                         
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _SP                     
                DEFB    _NL                     
MEMBOT:                                         
MEM0:           FLOAT   0                       
MEM1:           FLOAT   0                       
MEM2:           FLOAT   0                       
MEM3:           FLOAT   0                       
MEM4:           FLOAT   0                       
MEM5:           FLOAT   0                       
FREE2:          DEFW    0x0000                  

PROG:                                           

AUTOSTART_ADDR:                                 
DISPLAY:        DEFB    _NL                     
DSPLY00:        DEFB    _L,_I,_N,_E,_SP,_1      
                DEFB    _NL                     
DSPLY01:        DEFB    _L,_I,_N,_E,_SP,_2      
                DEFB    _NL                     
DSPLY02:        DEFB    _L,_I,_N,_E,_SP,_3      
                DEFB    _NL                     
DSPLY03:        DEFB    _L,_I,_N,_E,_SP,_4      
                DEFB    _NL                     
DSPLY04:        DEFB    _L,_I,_N,_E,_SP,_5      
                DEFB    _NL                     
DSPLY05:        DEFB    _L,_I,_N,_E,_SP,_6      
                DEFB    _NL                     
DSPLY06:        DEFB    _L,_I,_N,_E,_SP,_7      
                DEFB    _NL                     
DSPLY07:        DEFB    _L,_I,_N,_E,_SP,_8      
                DEFB    _NL                     
DSPLY08:        DEFB    _L,_I,_N,_E,_SP,_9      
                DEFB    _NL                     
DSPLY09:        DEFB    _L,_I,_N,_E,_SP,_1,_0   
                DEFB    _NL                     
DSPLY10:        DEFB    _L,_I,_N,_E,_SP,_1,_1   
                DEFB    _NL                     
DSPLY11:        DEFB    _L,_I,_N,_E,_SP,_1,_2   
                DEFB    _NL                     
DSPLY12:        DEFB    _L,_I,_N,_E,_SP,_1,_3   
                DEFB    _NL                     
DSPLY13:        DEFB    _L,_I,_N,_E,_SP,_1,_4   
                DEFB    _NL                     
DSPLY14:        DEFB    _L,_I,_N,_E,_SP,_1,_5   
                DEFB    _NL                     
DSPLY15:        DEFB    _L,_I,_N,_E,_SP,_1,_6   
                DEFB    _NL                     
DSPLY16:        DEFB    _L,_I,_N,_E,_SP,_1,_7   
                DEFB    _NL                     
DSPLY17:        DEFB    _L,_I,_N,_E,_SP,_1,_8   
                DEFB    _NL                     
DSPLY18:        DEFB    _L,_I,_N,_E,_SP,_1,_9   
                DEFB    _NL                     
DSPLY19:        DEFB    _L,_I,_N,_E,_SP,_2,_0   
                DEFB    _NL                     
DSPLY20:        DEFB    _L,_I,_N,_E,_SP,_2,_1   
                DEFB    _NL                     
DSPLY21:        DEFB    _L,_I,_N,_E,_SP,_2,_2   
                DEFB    _NL                     
DSPLY22:        DEFB    _L,_I,_N,_E,_SP,_2,_3   
                DEFB    _NL                     
DSPLY23:        DEFB    _L,_I,_N,_E,_SP,_2,_4   
                DEFB    _NL                     

VARIABLES:                                      


                DEFB    0x80                    
WORKSPACE:                                      


