//-----------------------------------------------------------------------------
// zx81dis
// Copyright (C) Paulo Custodio, 2023-2026
// License: The Artistic License 2.0, http://www.perlfoundation.org/artistic_license_2_0
//-----------------------------------------------------------------------------

#include "dis_analyse.h"
#include "dis_emit_bas.h"
#include "errors.h"
#include "utils.h"
#include "zx81chars.h"
#include "sysvars.h"
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>

static void emit_sysvars(std::ofstream& ofs, const Prog& prog) {
    ofs << "#SYSVARS =  ";
    size_t col = 12;
    for (uint addr = VERSN; addr < PROG; addr++) {
        if (addr > VERSN) {
            ofs << ",";
            col += 1;
        }
        if (col + 4 + 1 + 2 > 80) {
            ofs << " \\" << std::endl << "            ";
            col = 12;
        }
        ofs << int8_to_hex(prog.mem.peek(addr));
        col += 4;
    }
    ofs << std::endl;
}

static void emit_trailer(std::ofstream& ofs, const Prog& prog) {
    uint e_line = prog.mem.peek_word(E_LINE);
    uint eop = prog.mem.end_of_prog;
    if (e_line == eop) {
        return;
    }

    ofs << "#TRAILER =  ";
    size_t col = 12;
    for (uint addr = e_line; addr < eop; addr++) {
        if (addr > e_line) {
            ofs << ",";
            col += 1;
        }
        if (col + 4 + 1 + 2 > 80) {
            ofs << " \\" << std::endl << "            ";
            col = 12;
        }
        ofs << int8_to_hex(prog.mem.peek(addr));
        col += 4;
    }
    ofs << std::endl;
}

static void emit_header(std::ofstream& ofs, const Prog& prog) {
    ofs << "' Disassembly of " << prog.p_filename << std::endl;
    ofs << "' generated by z88dk-zx81dis" << std::endl;
    ofs << std::endl;

    ofs << "#INCREMENT = 1" << std::endl;

    // sysvars
    emit_sysvars(ofs, prog);
    emit_trailer(ofs, prog);

    // autostart
    int nxtlin = prog.mem.peek_word(NXTLIN);
    int d_file = prog.mem.peek_word(D_FILE);
    int autostart_line = prog.mem.peek_word_be(nxtlin);

    if (nxtlin == d_file) {
        ofs << "#AUTOSTART = 0" << std::endl;
    }
    else {
        ofs << "#AUTOSTART = 1" << std::endl;
        ofs << "#AUTOSTART_LINE = " << autostart_line << std::endl;
    }

    // FAST flag
    int cdflag = prog.mem.peek(CDFLAG);
    ofs << "#FAST = " << (cdflag == 0x40 ? false : true) << std::endl;

    ofs << std::endl;
}

static void emit_basic(std::ofstream& ofs, const Prog& prog) {
    for (const auto& line : prog.lines) {
        ofs << std::setw(5) << std::right << line.line_num << " ";
        for (const auto& token : line.tokens) {
            ofs << token.ws_before << token.text;
        }
        ofs << std::endl;

        if (line.asm_length > 0) {
            ofs << "#ASM" << std::endl;
            for (uint addr = line.asm_start_addr();
                    addr < line.asm_start_addr() + line.asm_length; ++addr) {
                uint8_t byte = prog.mem.peek(addr);
                ofs << std::setw(8) << " "
                    << std::left << std::setw(8) << "DEFB"
                    << int8_to_hex(byte) << " ; "
                    << int16_to_hex(addr) << " "
                    << zx81_char_name(byte) << std::endl;
            }
            ofs << "#ENDASM" << std::endl;
            ofs << std::endl;
        }
    }
    ofs << std::endl;
}

static void emit_display(std::ofstream& ofs, const Prog& prog) {
    if (prog.dfile.empty()) {
        return;
    }

    ofs << "#DFILE =";
    for (uint i = 0; i < 24 && i < prog.dfile.size(); ++i) {
        if (i > 0) {
            ofs << ", \\\n        ";
        }

        std::string text = prog.dfile[i];
        text = fixed_width_string(text, 32);    // cut extra chars
        text = str_trim(text);                  // remove end spaces

        ofs << "\"" << text << "\"";
    }
    ofs << std::endl;
    if (prog.dfile_colapsed) {
        ofs << "#DFILE_COLAPSED = 1" << std::endl;
    }
}

static void emit_vars(std::ofstream& ofs, const Prog& prog) {
    for (const auto& var : prog.variables) {
        if (var.is_loop_var) {
            ofs << "#VARS " << var.name << " = "
                << var.nvalues[0] << ","
                << var.limit << ","
                << var.step << ","
                << var.line_num
                << std::endl;
        }
        else if (var.is_string_var) {
            if (var.is_array_var) {
                ofs << "#VARS " << var.name << "(";
                bool first = true;
                for (const auto& dim : var.dims) {
                    if (!first) {
                        ofs << ",";
                    }
                    first = false;
                    ofs << dim;
                }
                ofs << ") = ";
                first = true;
                for (const auto& svalue : var.svalues) {
                    if (!first) {
                        ofs << ",";
                    }
                    first = false;
                    ofs << "\"" << svalue << "\"";
                }
                ofs << std::endl;
            }
            else {
                ofs << "#VARS " << var.name << " = \"" << var.svalues[0] << "\"" << std::endl;
            }
        }
        else {
            if (var.is_array_var) {
                ofs << "#VARS " << var.name << "(";
                bool first = true;
                for (const auto& dim : var.dims) {
                    if (!first) {
                        ofs << ",";
                    }
                    first = false;
                    ofs << dim;
                }
                ofs << ") = ";
                first = true;
                for (const auto& nvalue : var.nvalues) {
                    if (!first) {
                        ofs << ",";
                    }
                    first = false;
                    ofs << nvalue;
                }
                ofs << std::endl;
            }
            else {
                ofs << "#VARS " << var.name << " = " << var.nvalues[0] << std::endl;
            }
        }
    }
    ofs << std::endl;
}

void dis_emit_bas(const std::string& filename, const Prog& prog) {
    std::ofstream ofs(filename, std::ios::binary);
    if (!ofs) {
        fatal("Cannot open output file: " + filename);
    }

    emit_header(ofs, prog);
    emit_vars(ofs, prog);
    emit_basic(ofs, prog);
    emit_display(ofs, prog);
}
