name: build-on-ubuntu

on:
  push:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from git
      uses: actions/checkout@v5
      with: 
        submodules: 'true'
    - name: Update apt 
      run: |
        sudo apt update
    - name: Install apt dependencies
      run: |
        sudo apt install -y build-essential cpanminus libmodern-perl-perl liblocal-lib-perl
    - name: Install perl prerequisites
      run: |
        cpanm --local-lib=~/perl5 Modern::Perl Test::HexDifferences
    - name: Build
      run: |
        make
    - name: Run tests
      run: |
        make test
