name: build-on-windows-cygwin

on:
  push:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Configure git
      run: |
        git config --global core.autocrlf input
    - name: Checkout from git
      uses: actions/checkout@v5
      with: 
        submodules: 'true'
    - name: Install perl prerequisites
      env:
        PATH: C:\Strawberry\perl\bin;C:\Strawberry\c\bin;${{ env.PATH }}
      run: |
        cpan App::cpanminus
        cpanm Modern::Perl Path::Tiny Test::HexDifferences
    - name: Build
      run: |
        make
    - name: Run tests
      env:
        PATH: C:\Strawberry\perl\bin;C:\Strawberry\c\bin;${{ env.PATH }}
      run: |
        make test
